---
- include_role:
    name: lib_openshift

- name: Uninstall CFME - ManageIQ
  debug:
    msg: Uninstalling Cloudforms Management Engine - ManageIQ

- name: Ensure the CFME template is removed
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: absent
    kind: template
    name: manageiq

- name: Ensure the CFME SVC is removed
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: absent
    kind: svc
    selector: app=manageiq,template=manageiq

- name: Ensure the CFME PVs are removed
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: absent
    kind: pv
    name: "{{ item }}"
  with_items:
    - miq-pv01
    - miq-pv02
    - miq-pv03

- name: Ensure the CFME StatefulSet is removed
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: absent
    kind: statefulset
    selector: app=manageiq,template=manageiq

- name: Ensure the CFME NFS Exports are removed
  file:
    path: /etc/exports.d/openshift_cfme.exports
    state: absent
  register: nfs_exports_removed

- name: Ensure the NFS export table is refreshed if exports were removed
  command: exportfs -ar
  when: nfs_exports_removed.changed

- name: Ensure the CFME project is removed
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: absent
    kind: project
    name: "{{ openshift_cfme_project }}"

