---
- include_role:
    name: lib_openshift

- name: Uninstall CFME - ManageIQ
  debug:
    msg: Uninstalling Cloudforms Management Engine - ManageIQ

- name: Remove CFME templates
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: absent
    kind: template
    name: manageiq
