---
openshift_cfme_project: cfme2
openshift_cfme_project_description: ManageIQ - CloudForms Management Engine
openshift_cfme_user: cfme2
openshift_cfme_service_account: "system:serviceaccount:{{ openshift_cfme_project }}:default"
openshift_cfme_pv_templates:
  - miq-pv-db
  - miq-pv-region
  - miq-pv-server
openshift_cfme_maxImagesBulkImportedPerRepository: 100
openshift_cfme_nfs_server: "{{ groups.nfs.0 }}"
