---
# Namespace for the CFME project
openshift_cfme_project: openshift-cfme
# Namespace/project description
openshift_cfme_project_description: ManageIQ - CloudForms Management Engine 4.6
# [CONSTANT] Service Accounts
openshift_system_account_sccs:
  - name: tim
    resource_name: anyuid
  - name: miq-anyuid
    resource_name: anyuid
  - name: miq-orchestrator
    resource_name: anyuid
  - name: miq-privileged
    resource_name: privileged
  - name: miq-sysadmin
    resource_name: miq-sysadmin

openshift_cfme_system_account_roles:
  - name: miq-orchestrator
    resource_name: view
  - name: miq-orchestrator
    resource_name: edit

# Allowed options presently: nfs, external, preconfigured
openshift_cfme_storage_class: preconfigured


# All the required exports
openshift_cfme_pv_exports:
  - miq-pv01
  - miq-pv02
  - miq-pv03
# PV template files and their created object names
openshift_cfme_pv_data:
  - pv_name: miq-pv01
    pv_template: miq-pv-db.yaml
    pv_label: CFME DB PV
  - pv_name: miq-pv02
    pv_template: miq-pv-region.yaml
    pv_label: CFME Region PV
  - pv_name: miq-pv03
    pv_template: miq-pv-server.yaml
    pv_label: CFME Server PV

# TODO: Refactor '_install_app' variable. This is just for testing but
# maybe in the future it should control the entire yes/no for CFME.
#
# Whether or not the manageiq app should be initialized ('oc new-app
# --template=manageiq). If False everything UP TO 'new-app' is ran.
openshift_cfme_install_app: False
# Docker image to pull
openshift_cfme_application_img_name: "{{ 'registry.access.redhat.com/cloudforms45/cfme-openshift-app' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
openshift_cfme_postgresql_img_name: "{{ 'registry.access.redhat.com/cloudforms45/cfme-openshift-postgresql' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
openshift_cfme_memcached_img_name: "{{ 'registry.access.redhat.com/cloudforms45/cfme-openshift-memcached' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
openshift_cfme_application_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'app-latest-fine' }}"
openshift_cfme_memcached_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'memcached-latest-fine' }}"
openshift_cfme_postgresql_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'postgresql-latest-fine' }}"
