---
- name: Set up CFME
  hosts: masters
  roles:
  - openshift_cfme
  pre_tasks:
  - name: What are the groups?
    debug:
      var: groups.keys()

  - name: This is the beginning of the CFME plays
    debug:
      msg: "FIRST"
