---
# TODO: Make this work. The 'name' variable below is undefined
# presently because it's part of the cfme role. This play can't run
# until that's re-worked.
#
# - name: Pre-Pull manageiq-pods docker images
#   hosts: nodes
#   tasks:
#   - name: Ensure the latest manageiq-pods docker image is pulling
#     docker_image:
#       name: "{{ openshift_cfme_container_image }}"
#     # Fire-and-forget method, never timeout
#     async: 99999999999
#     # F-a-f, never check on this. True 'background' task.
#     poll: 0

- name: Setup CFME
  hosts: masters
  vars:
    r_openshift_cfme_miq_template_content: "{{ lookup('file', 'roles/openshift_cfme/files/miq-template.yaml') }}"
  tasks:
  - include_role:
    name: openshift_cfme
