---
- name: Setup CFME
  hosts: masters
  pre_tasks:
  - name: Create a temporary place to evaluate the PV templates
    command: mktemp -d /tmp/openshift-ansible-XXXXXXX
    register: g_cfme_mktemp
    changed_when: false

  roles:
  - role: openshift_cfme
    template_dir: "{{ hostvars[groups.masters.0].g_cfme_mktemp.stdout }}"
